### ISSUE TITLE
snapshotRequest cannot handle NA character strings in datatypes that return dates

### ISSUE THREAD

**Issue by miguellacerda** [CharlesCara/DatastreamDSWS2R#39]
In the code below, the NSR instrument returns "NA" while the other two return valid dates. However, the entire request fails due to the "NA" for NSR. 

```
mydsws$snapshotRequest(c("MYI","NEX","NSR"), datatype = 'TIME', requestDate = '0D')
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
```

I am using DatastreamDSWS2R version 1.7.2 in R version 4.0.2.

Is it not possible to replace the "NA" character string with NA_character_ so that it can be converted to an object of class Date?

**Comment by CharlesCara** [comment]
Please can you upgrade to version 1.7.5 - this was fixed in version 1.7.4.
```
> library(DatastreamDSWS2R) 
> mydsws <- dsws$new() 
> mydsws$snapshotRequest(c("MYI","NEX","NSR"), datatype = 'TIME', requestDate = '0D')
Instrument TIME 
1        MYI  2020-09-03 
2        NEX  2020-09-03 
3        NSR  <NA>
```

**Comment by miguellacerda** [comment]
I'm still seeing strange behaviour for some date fields that contain NAs. For example, this works as expected:
```
> mydsws$snapshotRequest(c("R:WARJ","R:IFRJ","R:WHLJ"), datatype = 'DEADDT', requestDate = '0D')

  Instrument     DEADDT
1     R:WARJ 2007-02-12
2     R:IFRJ 2008-05-30
3     R:WHLJ       <NA>
```
But removing the first ticker causes the date field to be returned as a character type:

```
> mydsws$snapshotRequest(c("R:IFRJ","R:WHLJ"), datatype = 'DEADDT', requestDate = '0D')

  Instrument DEADDT
1     R:IFRJ  14029
2     R:WHLJ     NA
```
I am using DatastreamDSWS2R version 1.7.9 from CRAN.

**Comment by CharlesCara** [comment]
The problem is that the DSWS service does not handle NA dates cleanly.  They are returned as "NA" with type 6 (character), and so these requests return a mixture of datatypes (Date and Character).  DatastreamDSWS2R checks uses the most common datatype to set the datatype of the column.  

If you know the expected datatype then you should force a conversion in your code after the request.

**Comment by miguellacerda** [comment]
Thanks so much for your response!

For columns that return a mixture of datatypes, is there no way to check if the elements of type character are all "NA"? If that's possible, then you could rather set the column to the other datatype (date, in this case) when all the character elements are "NA" (instead of using a majority vote to determine the column's datatype).

**Comment by CharlesCara** [comment]
That seems like a sensible idea.  Do you want to provide a pull request implementing it?  The code that would need to be amended is from line 1334 in classConstructor.R
