### ISSUE TITLE
Time series list request

### ISSUE THREAD

**Issue by awatt43** [CharlesCara/DatastreamDSWS2R#40]
Hi there

I am trying to pull through a time series of a number of datatypes for a list and I keep getting the following error. 

Command in R: testfords <- mydsws$timeSeriesListRequest(instrument="WSUS1",datatype = c("WC18198","WC01084"),startDate = "-2Y",endDate="0Y",frequency = "Y")

![image](https://user-images.githubusercontent.com/77967582/106129699-6685e780-6158-11eb-91cf-ebe706aff81c.png)

I have been assured by Refinitiv that this should be possible, am I doing something wrong? 

Thanks,
Abigail

**Comment by CharlesCara** [comment]
Hi Abigail

The request works for me:
```
> library(DatastreamDSWS2R) 
> mydsws <- dsws$new() 
> testfords <- mydsws$timeSeriesListRequest(instrument="WSUS1",datatype = c("WC18198","WC01084"),startDate = "-2Y",endDate="0Y",frequency = "Y") 
> testfords[[1]][1:2,1:5]            
          X544294 X883204 X916328 X699915 X328852 
2019-01-27      NA      NA 7761000      NA  212981 
2020-01-27      NA      NA      NA      NA      NA
```

I suggest that you restart your R session and change that you have the latest version of the package from CRAN:
```
update.packages("DatastreamDSWS2R")
```
You also might want to check that you are permissioned for this data by downloading it in Excel.

**Comment by awatt43** [comment]
Hi there

I have access to this through excel so I don't think it is a permissions issue.

Tried updating the package and the command still fails with the same error. 

I can pull through each datatype in separate requests but cannot pull in one single command?

Thanks
Abigail

**Comment by CharlesCara** [comment]
do you have the chunkLimit set to 50L?

**Comment by awatt43** [comment]
I tried changing the chunkLimit following from another issue on here, I changed this to 50L and now get a different error? 

![image](https://user-images.githubusercontent.com/77967582/106143843-427fd180-616b-11eb-92fc-3d59461fec09.png)

**Comment by CharlesCara** [comment]
Changing chunkLimit to 50L for me replicates the original error for me.   Here is a workaround where only one datatype is requested at a time and then these are combined into the final list.
```
testfords <- list(mydsws$timeSeriesListRequest(instrument="WSUS1",
                                               datatype = c("WC18198"),
                                               startDate = "-2Y",
                                               endDate="0Y",
                                               frequency = "Y"),
                  mydsws$timeSeriesListRequest(instrument="WSUS1",
                                               datatype = c("WC01084"),
                                               startDate = "-2Y",
                                               endDate="0Y",
                                               frequency = "Y"))
```

**Comment by awatt43** [comment]
Hi 

This work around doesn't seem to work for me either - I get the same server error.

I will try reinstalling and see if there is anything in my setup that could be causing these issues. 

Thank you for the help and suggestions thus far though.

Abigail

**Comment by CharlesCara** [comment]
My bug is fixed in v1.7.10, now on Github.  It can be installed with:

```
require(devtools)
install_github(“CharlesCara/DatastreamDSWS2R”)
```

**Comment by awatt43** [comment]
Hi 

I have reinstalled the package but I still get the same server error:
![image](https://user-images.githubusercontent.com/77967582/106281543-424d0800-6237-11eb-822c-91661e08c77e.png)

I can pull through a static list request but not a time series list request, in the normal form or the workaround which you suggested above.

Thanks
Abigail

**Comment by awatt43** [comment]
Just following up. This seems to be an intermittent issue. 

I just detatched the package then required it again and the time series requests are working now?

Thanks
Abigail
